services:
  - type: web
    name: currencyai
    rootDir: refactor
    plan: free
    env: python
    buildCommand: "./render-build.sh"
    startCommand: "cd backend && gunicorn app:app --workers 2 --timeout 120"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GEMINI_API_KEY
        sync: false
